name: Tests 🎳

on:
  push:
    tags:
      - '*'

jobs:

  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:

      - uses: actions/checkout@v2

      - name: Changelog
        id: changelog
        uses: 3liz/changelog-release@0.2.0

      - name: Create release on GitHub
        uses: ncipollo/release-action@v1.11.1
        with:
          body: ${{ steps.changelog.outputs.markdown }}
          token: ${{ secrets.BOT_HUB_TOKEN }}

      - name: Tweet
        uses: mugi111/tweet-trigger-release@v1.2
        with:
          consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          access_token_key: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          tweet_body: "Nouvelle version du module openADS ${{ env.RELEASE_VERSION }} 🏠 pour @LizmapForQgis et @openmairie https://github.com/3liz/lizmap-openads-module/releases"
