name: Tests 🎳

on:
  push:
    tags:
      - '*'

jobs:

  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')

    steps:

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2.3.1
        with:
          python-version: "3.10"

      - name: Install Python requirements
        run: pip install qgis-plugin-ci

      - name : Get current changelog
        run: qgis-plugin-ci changelog ${{ env.RELEASE_VERSION }} >> release.md

      - name: Create release on GitHub
        uses: ncipollo/release-action@v1.9.0
        with:
          bodyFile: release.md
          token: ${{ secrets.BOT_HUB_TOKEN }}

      - name: Tweet
        uses: mugi111/tweet-trigger-release@v1.2
        with:
          consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          access_token_key: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
          access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          tweet_body: "Nouvelle version du module openADS ${{ env.RELEASE_VERSION }} 🏠 pour @LizmapForQgis et @openmairie https://github.com/3liz/lizmap-openads-module/releases"
